[build]
  command = "CI=false npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_VERSION = "9.6.7"
  NETLIFY_USE_YARN = "false"

# Increase build timeout for large projects
[build.processing]
  skip_processing = false

# Handle SPA routing for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle Supabase auth callback
[[redirects]]
  from = "/.netlify/functions/auth"
  to = "/.netlify/functions/auth"
  status = 200 